const SERVICES_ACTION_TYPES = {
  SET_SERVICES_MAP: 'services/SET_SERVICES_MAP',
  SET_SERVICES: 'services/SET_SERVICES',
  FETCH_SERVICES_START: 'services/FETCH_SERVICES_START',
  FETCH_SERVICES_SUCCESS: 'services/FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_FAILED: 'services/FETCH_SERVICES_FAILED'
};

export default SERVICES_ACTION_TYPES;