const BLOGS_ACTION_TYPES = {
  SET_BLOGS_MAP: 'blogs/SET_BLOGS_MAP',
  SET_BLOGS: 'blogs/SET_BLOGS',
  FETCH_BLOGS_START: 'blogs/FETCH_BLOGS_START',
  FETCH_BLOGS_SUCCESS: 'blogs/FETCH_BLOGS_SUCCESS',
  FETCH_BLOGS_FAILED: 'blogs/FETCH_BLOGS_FAILED'
};

export default BLOGS_ACTION_TYPES;